import { defineCollection, z } from 'astro:content';
import { glob } from 'astro/loaders';
const programs = defineCollection({ loader: glob({pattern:'**/*.{md,mdx}',base:'./src/content/programs'}), schema:z.object({title:z.string(),summary:z.string(),icon:z.string().default('heart'),order:z.number().default(1),featured:z.boolean().default(true),draft:z.boolean().default(false),supportItems:z.array(z.string()).default([])}) });
const stories = defineCollection({ loader: glob({pattern:'**/*.{md,mdx}',base:'./src/content/stories'}), schema:z.object({title:z.string(),excerpt:z.string(),date:z.coerce.date(),image:z.string().optional(),featured:z.boolean().default(false),draft:z.boolean().default(true),personName:z.string().optional(),location:z.string().optional()}) });
const updates = defineCollection({ loader: glob({pattern:'**/*.{md,mdx}',base:'./src/content/updates'}), schema:z.object({title:z.string(),excerpt:z.string(),date:z.coerce.date(),category:z.string(),image:z.string().optional(),draft:z.boolean().default(true)}) });
const impactMetrics = defineCollection({ loader: glob({pattern:'**/*.{md,mdx}',base:'./src/content/impact-metrics'}), schema:z.object({title:z.string(),date:z.coerce.date(),periodLabel:z.string().optional(),volunteers:z.number().int().nonnegative().default(0),partners:z.number().int().nonnegative().default(0),fundraisers:z.number().int().nonnegative().default(0),programSupporters:z.number().int().nonnegative().default(0),familiesSupported:z.number().int().nonnegative().default(0),draft:z.boolean().default(true)}) });
const team = defineCollection({ loader: glob({pattern:'**/*.{md,mdx}',base:'./src/content/team'}), schema:z.object({name:z.string(),role:z.string(),photo:z.string().optional(),order:z.number().default(1),draft:z.boolean().default(false)}) });
const reports = defineCollection({ loader: glob({pattern:'**/*.{md,mdx}',base:'./src/content/reports'}), schema:z.object({title:z.string(),date:z.coerce.date().optional(),year:z.number().optional(),type:z.string(),file:z.string().optional(),images:z.array(z.string()).default([]),draft:z.boolean().default(true)}) });
export const collections={programs,stories,updates,impactMetrics,team,reports};
